// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined) ||
  (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
  (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

function createStubClient(): SupabaseClient<Database> {
  const notConfigured = async () => ({
    data: null,
    error: { message: 'Supabase is not configured. Enable Lovable Cloud to use auth/database.' },
  });
  const authStub = {
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: (_cb: unknown) => ({
      data: { subscription: { unsubscribe: () => {} } },
    }),
    signInWithPassword: notConfigured,
    signUp: notConfigured,
    signInWithOAuth: notConfigured,
    signOut: async () => ({ error: null }),
  };
  const queryStub: any = {
    select: () => queryStub,
    insert: () => queryStub,
    update: () => queryStub,
    upsert: () => queryStub,
    delete: () => queryStub,
    eq: () => queryStub,
    neq: () => queryStub,
    in: () => queryStub,
    order: () => queryStub,
    then: (resolve: (v: unknown) => void) => resolve({ data: [], error: null }),
  };
  return {
    auth: authStub,
    from: () => queryStub,
  } as unknown as SupabaseClient<Database>;
}

let _supabase: SupabaseClient<Database> | undefined;
function getClient(): SupabaseClient<Database> {
  if (_supabase) return _supabase;
  if (!isSupabaseConfigured) {
    if (typeof window !== 'undefined') {
      console.warn(
        '[supabase] Not configured — running in offline stub mode. Enable Lovable Cloud to enable auth/database.',
      );
    }
    _supabase = createStubClient();
    return _supabase;
  }
  _supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    return Reflect.get(getClient(), prop, receiver);
  },
});
